---
title: "From Override to Activation"
subtitle: "The Pharmaceutical Paradigm Shift"
author: "Norbert Marchewka"
date: \today
lang: en-US

# Pandoc options
pdf-engine: xelatex
template: templates/english-elegant.tex
toc: false
number-sections: false

# Formatting
fontsize: 12pt
documentclass: article
classoption:
  - 12pt
  - a4paper

# Syntax highlighting
highlight-style: tango
---
